[pytest]
testpaths = tests
norecursedirs =
    .git
    .pytest_cache
    backups
    patch
    patches
    updates
    update
    update-packages
    update_packages
    release-packages
    release_packages
    deployments
    data
    AFDE_2_2_UPDATE_PACKAGE
